-- MySQL Script generated by MySQL Workbench
-- Tue May 16 22:26:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_password` VARCHAR(45) NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `estado` BINARY NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`saldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`saldo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_saldo` DATE NOT NULL,
  `valor_saldo` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ciudad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `departamento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_departamento_ciudad_idx` (`departamento_id` ASC),
  CONSTRAINT `fk_departamento_ciudad`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `mydb`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(255) NOT NULL,
  `documento` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_venta` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `valor_venta` DOUBLE NOT NULL,
  `ciudad_id` INT NULL,
  `usuario_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ciudad_venta_idx` (`ciudad_id` ASC),
  INDEX `fk_usuario_venta_idx` (`usuario_id` ASC),
  INDEX `fk_cliente_venta_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_ciudad_venta`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `mydb`.`ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_venta`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_venta`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_articulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_articulo` VARCHAR(255) NOT NULL,
  `tipo_articulo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipo_articulo_articulo_idx` (`tipo_articulo_id` ASC),
  CONSTRAINT `fk_tipo_articulo_articulo`
    FOREIGN KEY (`tipo_articulo_id`)
    REFERENCES `mydb`.`tipo_articulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `origen` VARCHAR(1) NOT NULL,
  `articulo_id` INT NOT NULL,
  `estado` BINARY NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_inventario_articulo1_idx` (`articulo_id` ASC),
  CONSTRAINT `fk_inventario_articulo1`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `mydb`.`articulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empeno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empeno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `fecha_vencimiento` DATE NOT NULL,
  `cliente_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_id_idx` (`cliente_id` ASC),
  INDEX `fk_usuario_id_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empeno_articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empeno_articulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor_articulo` DOUBLE NOT NULL,
  `empeno_id` INT NOT NULL,
  `articulo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empeno_idx` (`empeno_id` ASC),
  INDEX `fk_articulo_empeno_articulo_idx` (`articulo_id` ASC),
  UNIQUE INDEX `empeno_id_UNIQUE` (`empeno_id` ASC),
  CONSTRAINT `fk_empeno_empeno_articulo`
    FOREIGN KEY (`empeno_id`)
    REFERENCES `mydb`.`empeno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulo_empeno_articulo`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `mydb`.`articulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`abono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`abono` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor_abono` DOUBLE NOT NULL,
  `fecha_abono` DATE NOT NULL,
  `empeno_articulo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empeno_articulo_idx` (`empeno_articulo_id` ASC),
  CONSTRAINT `fk_empeno_articulo`
    FOREIGN KEY (`empeno_articulo_id`)
    REFERENCES `mydb`.`empeno_articulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inventario_id` INT NOT NULL,
  `venta_id` INT NOT NULL,
  `valor_articulo` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_venta_inventario1_idx` (`inventario_id` ASC),
  INDEX `fk_detalle_venta_venta1_idx` (`venta_id` ASC),
  CONSTRAINT `fk_detalle_venta_inventario1`
    FOREIGN KEY (`inventario_id`)
    REFERENCES `mydb`.`inventario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_venta_venta1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `mydb`.`venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
